[theme]
primaryColor = "#4A148C"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F5F5F5"
textColor = "#212121"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
